### ISSUE TITLE
有关表格边框粗细、标题样式和正文字号的疑问

### ISSUE THREAD

**Issue by Robotxm** [note286/xduugtp#2]
首先感谢提供如此方便的模板。

在使用过程中，我发现有些地方的样式和 2022 年给出的模板有些出入。目前我注意到的地方有表格边框粗细、标题和正文字号这几个地方。

使用学校公布的 Word 模板编辑样式如下图所示：
![image](https://user-images.githubusercontent.com/5405331/157275483-3bb36814-aed9-4258-a163-f1dc54c965b5.png)

而使用此 LaTeX 模板生成的 PDF 样式如下所示：
![image](https://user-images.githubusercontent.com/5405331/157275563-dc0231ea-07bd-4b7e-9a37-d748e382af3e.png)

我查看了 Word 中的样式设定，发现表格边框粗细为 0.5 磅，标题样式为“小四，不加粗”，正文字号为“四号”。与 LaTeX 中的设定不一致。

我本地的环境是 Windows 11 + TeX Live 2021。所下载的模板压缩包是这个：[毕业设计（论文）表格.zip](https://github.com/note286/xduugtp/files/8207641/default.zip)，来源为一站式网上服务大厅里的“毕业设计”系统。还辛苦作者查看一下。

以上。

**Comment by note286** [comment]
我认为正文四号是教务处弄错了，一级标题是小四，正文比一级标题字号还大，这不符合常理。

另外，我之所以设置标题样式为粗体，就是因为标题字号过小，如果不用粗体，很不美观，与正文无法区分，不过粗体目前我已经移除了。

**Comment by Robotxm** [comment]
感谢回复与更新。

确实如果使用粗体的话会更加美观一些，但是不知道教务处是否允许修改标题为粗体。

正文字号我也比较赞同您的看法，倾向于是教务处的失误。
